name: main

on:
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/main.yml'
      - '*.go'
      - 'Dockerfile'
      - 'internal/**'
      - 'go.*'
      - 'Makefile'
      - 'pkg/**'

jobs:

  version:
    runs-on: ubuntu-latest
    container: mpdred/semantic-tagger:latest
    steps:

      - uses: actions/checkout@v2
        with:
          fetch-depth: 50

      - name: Set the version number
        run: |
          git config --global user.email "ci@redstonepointers.com"
          git config --global user.name "ci"
          semtag -increment=auto -git-tag -push -prefix=v

      - name: Persist the version number to disk
        run: |
          semtag | tail -1 > .version.txt
          cat .version.txt

      - name: Upload the version file
        uses: actions/upload-artifact@v2
        with:
          name: version-file
          path: .version.txt
          retention-days: 1

  build-base-image:
    runs-on: ubuntu-latest
    steps:

      # The `install` flag sets up docker build command as an alias to docker buildx
      # see: https://github.com/docker/setup-buildx-action#inputs
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - uses: actions/checkout@v2

      - name: Build and push base Docker image
        uses: docker/build-push-action@v2
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: .
          push: false
          target: dependencies

  build:
    runs-on: ubuntu-latest
    needs: [ version, build-base-image ]
    steps:

      - name: Download the version file
        uses: actions/download-artifact@v2
        with:
          name: version-file

      - name: Export the version number
        run: |
          test -f .version.txt
          export VERSION_NUMBER="$(cat .version.txt)"
          echo "Export version: $VERSION_NUMBER"
          echo "::set-output name=VERSION_NUMBER::$VERSION_NUMBER"
        id: version-number

      # The `install` flag sets up docker build command as an alias to docker buildx
      # see: https://github.com/docker/setup-buildx-action#inputs
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          cache-from: type=gha
          context: .
          push: true
          tags: |
            "${{ github.repository }}:${{ steps.version-number.outputs.VERSION_NUMBER }}"
            "${{ github.repository }}:latest"

  test:
    runs-on: ubuntu-latest
    needs: [ build-base-image ]
    steps:

      # The `install` flag sets up docker build command as an alias to docker buildx
      # see: https://github.com/docker/setup-buildx-action#inputs
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - uses: actions/checkout@v2

      - name: Execute unit tests
        uses: docker/build-push-action@v2
        with:
          cache-from: type=gha
          context: .
          push: false
          target: test
