name: PRs

on:
  pull_request:
    paths:
      - '.github/workflows/pr.yml'
      - '*.go'
      - 'Dockerfile'
      - 'internal/**'
      - 'go.*'
      - 'Makefile'
      - 'pkg/**'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      # The `install` flag sets up docker build command as an alias to docker buildx
      # see: https://github.com/docker/setup-buildx-action#inputs
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - uses: actions/checkout@v2

      - name: Build
        uses: docker/build-push-action@v2
        with:
          cache-from: type=gha
          context: .
          push: false

  test:
    runs-on: ubuntu-latest
    steps:

      # The `install` flag sets up docker build command as an alias to docker buildx
      # see: https://github.com/docker/setup-buildx-action#inputs
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - uses: actions/checkout@v2

      - name: Execute unit tests
        uses: docker/build-push-action@v2
        with:
          cache-from: type=gha
          context: .
          push: false
          target: test
